# Probability distributions


Name | parameters | support | pdf/pmf | mean | variance
--- | --- | --- | --- | --- | ---
Bernoulli | $p \in [0,1]$ | $k \in \{0,1\}$ | $p^k (1 - p)^{1 - k}$ <br> \@ref(exr:binomialpmf) | $p$ <br> \@ref(exr:Bernev) |  $p(1-p)$ <br> \@ref(exr:Bernev)
binomial |$n \in \mathbb{N}$, $p \in [0,1]$| $k \in \{0,1,\dots,n\}$ | $\binom{n}{k} p^k (1 - p)^{n - k}$ <br> \@ref(exr:bincdf) |$np$ <br> \@ref(exr:binomev) |  $np(1-p)$ <br> \@ref(exr:binomev)
Poisson |$\lambda > 0$| $k \in \mathbb{N}_0$ | $\frac{\lambda^k e^{-\lambda}}{k!}$ <br> \@ref(exr:poisex) |  $\lambda$ <br> \@ref(exr:poisev) | $\lambda$ <br> \@ref(exr:poisev)
geometric | $p \in (0,1]$ | $k \in \mathbb{N}_0$ | $p(1-p)^k$ <br> \@ref(exr:geocdf) | $\frac{1 - p}{p}$ <br> \@ref(exr:geoev)| $\frac{1 - p}{p^2}$ <br> \@ref(exr:geovar)
normal |$\mu \in \mathbb{R}$, $\sigma^2 > 0$ | $x \in \mathbb{R}$ |$\frac{1}{\sqrt{2 \pi \sigma^2}} e^{-\frac{(x - \mu)^2}{2 \sigma^2}}$ <br> \@ref(exr:normalpdf) | $\mu$ \@ref(exr:normev) | $\sigma^2$ \@ref(exr:normev)
uniform |$a,b \in \mathbb{R}$, $a < b$| $x \in [a,b]$ | $\frac{1}{b-a}$ <br> \@ref(exr:unifpdf) | $\frac{a+b}{2}$ | $\frac{(b-a)^2}{12}$
beta |$\alpha,\beta > 0$| $x \in [0,1]$ | $\frac{x^{\alpha - 1} (1 - x)^{\beta - 1}}{\text{B}(\alpha, \beta)}$ <br> \@ref(exr:betacdf) | $\frac{\alpha}{\alpha + \beta}$ \@ref(exr:betaev)| $\frac{\alpha \beta}{(\alpha + \beta)^2(\alpha + \beta + 1)}$ \@ref(exr:betaev)
gamma |$\alpha,\beta > 0$| $x \in (0, \infty)$ | $\frac{\beta^\alpha}{\Gamma(\alpha)} x^{\alpha - 1}e^{-\beta x}$  <br> \@ref(exr:gammapdf) |$\frac{\alpha}{\beta}$ <br> \@ref(exr:gammaev) | $\frac{\alpha}{\beta^2}$ <br> \@ref(exr:gammaev)
exponential |$\lambda > 0$| $x \in [0, \infty)$ | $\lambda e^{-\lambda x}$ <br> \@ref(exr:expcdf) |$\frac{1}{\lambda}$ <br> \@ref(exr:expev)   |$\frac{1}{\lambda^2}$ <br> \@ref(exr:expev)
logistic |$\mu \in \mathbb{R}$, $s > 0$| $x \in \mathbb{R}$ | $\frac{e^{-\frac{x - \mu}{s}}}{s(1 + e^{-\frac{x - \mu}{s}})^2}$ <br> \@ref(exr:logitpdf) | $\mu$ | $\frac{s^2 \pi^2}{3}$
negative binomial |$r \in \mathbb{N}$, $p \in [0,1]$| $k \in \mathbb{N}_0$ | $\binom{k + r - 1}{k}(1-p)^r p^k$ <br> \@ref(exr:negbinpdf) | $\frac{rp}{1 - p}$ <br> \@ref(exr:nbev)| $\frac{rp}{(1 - p)^2}$ <br> \@ref(exr:nbev)
multinomial |$n \in \mathbb{N}$, $k \in \mathbb{N}$ $p_i \in [0,1]$, $\sum p_i = 1$  | $x_i \in \{0,..., n\}$, $i \in \{1,...,k\}$, $\sum{x_i} = n$ | $\frac{n!}{x_1!x_2!...x_k!} p_1^{x_1} p_2^{x_2}...p_k^{x_k}$ <br> \@ref(exr:mnompdf) | $np_i$ | $np_i(1-p_i)$
<!-- multivariate normal |$\frac{1}{(2 \pi)^{-\frac{k}{2}}} \text{det}(\Sigma)^{-\frac{1}{2}} \exp(-\frac{1}{2}(x - \mu)^T \Sigma^{-1} (x - \mu))$ | | |  -->





